Traceback (most recent call last):
  File "/tmp/pbs.9088127.pbs/fixedpointpot.py", line 220, in <module>
    anim.save('anim.mp4', writer=writervideo)
  File "/rds/general/user/mf620/home/anaconda3/lib/python3.11/site-packages/matplotlib/animation.py", line 1105, in save
    anim._draw_next_frame(d, blit=False)
  File "/rds/general/user/mf620/home/anaconda3/lib/python3.11/site-packages/matplotlib/animation.py", line 1140, in _draw_next_frame
    self._draw_frame(framedata)
  File "/rds/general/user/mf620/home/anaconda3/lib/python3.11/site-packages/matplotlib/animation.py", line 1768, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pbs.9088127.pbs/fixedpointpot.py", line 205, in update_plot
    plt.scatter(400*overall_array_x_stable[ii],400*overall_array_y_stable[ii],c='red',s=0.5)
                    ~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
